version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.32.5
    depends_on:
      - prometheus
    volumes:
      - ./thanos:/etc/thanos
    command:
      - sidecar
      - --http-address=0.0.0.0:19191
      - --grpc-address=0.0.0.0:19090
      - --prometheus.url=http://prometheus:9090
    ports:
      - "19191:19191"
      - "19090:19090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning  # Mount the provisioning config
    depends_on:
      - prometheus
    networks:
      - monitoring

  nextjs:
    build:
      context: ./nextjs
    ports:
      - '3000:3000'
    networks:
      - monitoring
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=256 # Intentionally low to trigger GC
    depends_on:
      - prometheus

networks:
  monitoring:

volumes:
  grafana-storage: