global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'localapp'
    metrics_path: '/api/prometheus'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          group: 'local'